(()=>{
  const user=window.BRAINTRUST_USER||{role:"member",capabilities:["chat"]},caps=new Set(Array.isArray(user.capabilities)?user.capabilities:[]),can=x=>caps.has(x);
  const say=(text,type="system")=>typeof notice==="function"?notice(`*** ${text}`,type):console.log(text);
  function secretModal(title,code,note=""){const shade=document.createElement("div");shade.style.cssText="position:fixed;inset:0;z-index:100000;background:#000b;display:grid;place-items:center;padding:18px";const card=document.createElement("div");card.style.cssText="width:min(430px,94vw);background:#0b151f;border:1px solid #4b7395;border-radius:12px;padding:16px;color:#e7edf2;font-family:Menlo,monospace";card.innerHTML=`<b style="color:#f0c85b">${safe(title)}</b><p style="font-size:10px;color:#9fb3c3;line-height:1.45">${safe(note||"Save this privately. It will not be shown again.")}</p><input readonly value="${safe(code)}" style="box-sizing:border-box;width:100%;padding:10px;background:#03080c;color:#fff;border:1px solid #35516b;border-radius:7px;font:12px Menlo,monospace"><div style="display:flex;gap:8px;margin-top:10px"><button data-copy style="flex:1;padding:8px">COPY</button><button data-close style="flex:1;padding:8px">CLOSE</button></div>`;shade.appendChild(card);document.body.appendChild(shade);card.querySelector("[data-copy]").onclick=async()=>{try{await navigator.clipboard.writeText(code);card.querySelector("[data-copy]").textContent="COPIED ✓"}catch{}};card.querySelector("[data-close]").onclick=()=>shade.remove()}
  function changeCard(result){const box=document.createElement("div");box.className="line system";box.style.cssText="border-left:2px solid #5a88aa;padding:7px;margin:7px 0;background:#0e1821";const pr=Number(result.pr||0);box.innerHTML=`<b>CHANGE PROPOSAL #${pr}</b><br><span>${safe(result.summary||"Preview prepared.")}</span><br><small>Production is unchanged until owner approval.</small><br>`;const row=document.createElement("div");row.style.cssText="display:flex;gap:5px;flex-wrap:wrap;margin-top:6px";const statusBtn=document.createElement("button");statusBtn.textContent="CHECK PREVIEW";statusBtn.onclick=()=>runCommand(`/pr ${pr}`);row.appendChild(statusBtn);if(can("approve")){const approve=document.createElement("button");approve.textContent="APPROVE";approve.onclick=()=>runCommand(`/approve ${pr}`);row.appendChild(approve)}if(can("reject")){const reject=document.createElement("button");reject.textContent="REJECT";reject.onclick=()=>runCommand(`/reject ${pr}`);row.appendChild(reject)}box.appendChild(row);chat.appendChild(box);chat.scrollTop=chat.scrollHeight}
  function statusCard(data){const box=document.createElement("div");box.className="line system";box.style.cssText="border-left:2px solid #5a88aa;padding:7px;margin:7px 0;background:#0e1821";const checks=(data.checks||[]).map(x=>`${x.name}: ${x.status}/${x.conclusion||"…"}`).join("<br>")||`Combined status: ${safe(data.combinedState||"pending")}`;box.innerHTML=`<b>PR #${safe(data.pr)}</b> · ${data.ready?"READY":"WAITING"}<br>${checks}<br>${data.previewUrl?`<a href="${safe(data.previewUrl)}" target="_blank" rel="noopener">OPEN VERCEL PREVIEW</a><br>`:""}<small>Mergeable: ${safe(String(data.mergeable))}. Production remains unchanged until APPROVE.</small>`;if(can("approve")||can("reject")){const row=document.createElement("div");row.style.cssText="display:flex;gap:5px;margin-top:6px";if(can("approve")){const b=document.createElement("button");b.textContent="APPROVE";b.disabled=!data.ready;b.onclick=()=>runCommand(`/approve ${data.pr}`);row.appendChild(b)}if(can("reject")){const b=document.createElement("button");b.textContent="REJECT";b.onclick=()=>runCommand(`/reject ${data.pr}`);row.appendChild(b)}box.appendChild(row)}chat.appendChild(box);chat.scrollTop=chat.scrollHeight}
  async function post(url,body){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data}
  async function get(url){const r=await fetch(url,{cache:"no-store"}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data}
  async function runCommand(raw){const[cmd,...rest]=String(raw||"").trim().split(/\s+/),arg=rest.join(" ").trim();try{
    if(cmd==="/propose"){if(!can("propose"))throw Error("Your account may discuss changes but cannot create architecture proposals.");if(arg.length<8)throw Error("Usage: /propose describe the change");say("Creating isolated candidate branch, backup tag and preview…");changeCard(await post("/api/gate?target=autopilot",{action:"propose",task:arg}));return true}
    if(cmd==="/pr"){if(!can("preview"))throw Error("Preview permission required.");const pr=Number(rest[0]);if(!pr)throw Error("Usage: /pr 42");statusCard(await post("/api/gate?target=autopilot",{action:"status",pr}));return true}
    if(cmd==="/approve"){if(!can("approve"))throw Error("Only the owner can approve production.");const pr=Number(rest[0]);if(!pr)throw Error("Usage: /approve 42");if(!confirm(`APPROVE PR #${pr} FOR PRODUCTION?\n\nThis is the explicit owner gate.`))return true;const data=await post("/api/gate?target=autopilot",{action:"approve",pr});say(data.message||`PR #${pr} approved.`);return true}
    if(cmd==="/reject"){if(!can("reject"))throw Error("Only the owner can reject deployment proposals.");const pr=Number(rest[0]);if(!pr)throw Error("Usage: /reject 42");const data=await post("/api/gate?target=autopilot",{action:"reject",pr});say(data.message||`PR #${pr} rejected.`);return true}
    if(cmd==="/rollback"){if(!can("rollback"))throw Error("Only the owner can roll production back.");if(!arg)throw Error("Usage: /rollback arena-backup-YYYYMMDDHHMMSS");if(!confirm(`ROLL BACK PRODUCTION TO ${arg}?`))return true;const data=await post("/api/gate?target=autopilot",{action:"rollback",backup:arg});say(data.message||"Rollback started.");return true}
    if(cmd==="/users"){if(!can("manage_users"))throw Error("Owner permission required.");const data=await get("/api/users");(data.users||[]).forEach(u=>say(`${u.nick} · ${u.role.toUpperCase()} · ${u.active?"ACTIVE":"REVOKED"} · rev ${u.rev}`));return true}
    if(cmd==="/invite"){if(!can("manage_users"))throw Error("Owner permission required.");const nick=rest[0]||"",role=(rest[1]||"member").toLowerCase(),data=await post("/api/users",{action:"create",nick,role});secretModal(`ACCESS CODE — ${data.nick}`,data.code,`${data.role.toUpperCase()} credential. ${data.note||""}`);return true}
    if(cmd==="/revoke"){if(!can("manage_users"))throw Error("Owner permission required.");const nick=rest[0]||"";if(!nick)throw Error("Usage: /revoke Nick");await post("/api/users",{action:"revoke",nick});say(`${nick} revoked.`);return true}
    if(cmd==="/role"){if(!can("manage_users"))throw Error("Owner permission required.");const nick=rest[0]||"",role=(rest[1]||"").toLowerCase();if(!nick||!role)throw Error("Usage: /role Nick member|maintainer");await post("/api/users",{action:"role",nick,role});say(`${nick} role changed to ${role}.`);return true}
    if(cmd==="/rotate"){if(!can("manage_users"))throw Error("Owner permission required.");const nick=rest[0]||"";if(!nick)throw Error("Usage: /rotate Nick");const data=await post("/api/users",{action:"rotate",nick});secretModal(`NEW ACCESS CODE — ${data.nick}`,data.code,data.note||"Old credentials are revoked.");return true}
    if(cmd==="/freeze"){if(!can("manage_security"))throw Error("Owner permission required.");const reason=arg||"Owner emergency lockdown";if(!confirm("LOCK DOWN THE BRAIN TRUST?\n\nChat and deployments will stop after redeploy. Rollback/security controls remain available."))return true;const data=await post("/api/security",{action:"freeze",reason});say(`LOCKDOWN requested: ${data.policy.reason}`);return true}
    if(cmd==="/unfreeze"){if(!can("manage_security"))throw Error("Owner permission required.");await post("/api/security",{action:"unfreeze"});say("Unlock requested.");return true}
    if(cmd==="/security"){if(!can("manage_security"))throw Error("Owner permission required.");const data=await get("/api/security");say(`Security: ${data.policy.frozen?"LOCKED":"ACTIVE"} · ${data.policy.reason||"normal operations"}`);return true}
    return false
  }catch(e){say(e.message||String(e),"error");return true}}
  window.BRAINTRUST_CONTROL={runCommand,user};
  const oldSend=send;
  send=async function(spokenText=""){const raw=String((spokenText&&typeof spokenText!=="object"?spokenText:"")||input.value||"").trim();if(/^\/(propose|pr|approve|reject|rollback|users|invite|revoke|role|rotate|freeze|unfreeze|security)\b/i.test(raw)){input.value="";return runCommand(raw)}return oldSend(spokenText)};
  if(can("propose"))say(`Control plane ready · ${user.role.toUpperCase()} · proposals never change production until explicit owner approval.`);
})();
